language: php

dist: xenial

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - composer install

before_script:
  - ./.before_script.sh

script:
  - vendor/bin/phpunit --verbose
